# 3. Practicing Scikit-Learn Syntax
Let's get good with Scikit-learn during this notebook.

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.options.display.max_columns = 100
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')




heart = pd.read_csv('../data/heart.csv')
heart.head()

age     sex    chest_pain  rest_bp  chol  fbs  \
0   63    Male       typical      145   233    1   
1   67    Male  asymptomatic      160   286    0   
2   67    Male  asymptomatic      120   229    0   
3   37    Male    nonanginal      130   250    0   
4   41  Female    nontypical      130   204    0   

                        rest_ecg  max_hr  exang  old_peak  slope   ca  \
0  left ventricular hypertrophy      150      0       2.3      3  0.0   
1  left ventricular hypertrophy      108      1       1.5      2  3.0   
2  left ventricular hypertrophy      129      1       2.6      2  2.0   
3                         normal     187      0       3.5      3  0.0   
4  left ventricular hypertrophy      172      0       1.4      1  0.0   

         thal  disease  
0       fixed        0  
1      normal        1  
2  reversable        1  
3      normal        0  
4      normal        0

# Let's build many different models from different parts of the library slowly adding more features
* Let's build decision trees, random forests, K-Nearest Neighbors and Support vector machines:
* Predict, then Score, and write down your scores

In [3]:
X = heart['rest_bp'].values
X = X.reshape(-1, 1)
y = heart['disease'].values

In [4]:
from sklearn.linear_model import LogisticRegression

In [5]:
#step2 - instantiatin with default 
logr = LogisticRegression()

In [9]:
#step3 - train with fit method 
logr.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [7]:
logr.score(X, y)

0.5676567656765676

In [ ]:
# Score with rest_bp with logistic regression was .57

# Next machine learning model

In [17]:
# step 0 - get numpy array values 
X = heart['chol'].values
X = X.reshape(-1, 1)
y = heart['disease'].values

In [18]:
# step 1 - import 
from sklearn.tree import DecisionTreeClassifier

In [19]:
dtc = DecisionTreeClassifier()

In [20]:
# train with fit method 
dtc.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf='deprecated', min_samples_split=2,
            min_weight_fraction_leaf='deprecated', presort=False,
            random_state=None, splitter='best')

In [21]:
dtc.score(X, y)

0.8151815181518152

In [22]:
# score is .81

# Random Forest 

In [23]:
X = heart['chol'].values
X = X.reshape(-1, 1)
y = heart['disease']


In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rfc = RandomForestClassifier()

In [26]:
rfc.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf='deprecated', min_samples_split=2,
            min_weight_fraction_leaf='deprecated', n_estimators=10,
            n_jobs=None, oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [27]:
rfc.score(X, y)

0.801980198019802

In [31]:
rfc.classes_

array([0, 1])

In [32]:
# the score is 0.8 
rfc.predict_proba(X)

array([[0.87642857, 0.12357143],
       [0.        , 1.        ],
       [0.075     , 0.925     ],
       [0.9       , 0.1       ],
       [0.53665584, 0.46334416],
       [0.72666667, 0.27333333],
       [0.41833333, 0.58166667],
       [0.7       , 0.3       ],
       [0.15064935, 0.84935065],
       [0.365     , 0.635     ],
       [1.        , 0.        ],
       [0.26666667, 0.73333333],
       [0.27261905, 0.72738095],
       [0.67333333, 0.32666667],
       [1.        , 0.        ],
       [0.8       , 0.2       ],
       [0.075     , 0.925     ],
       [0.51166667, 0.48833333],
       [0.48      , 0.52      ],
       [0.53333333, 0.46666667],
       [1.        , 0.        ],
       [0.1875    , 0.8125    ],
       [0.        , 1.        ],
       [0.35833333, 0.64166667],
       [0.1       , 0.9       ],
       [0.71      , 0.29      ],
       [0.6       , 0.4       ],
       [1.        , 0.        ],
       [0.52619048, 0.47380952],
       [0.        , 1.        ],
       [0.

# Classifier 

In [33]:
heart.head(2)

age   sex    chest_pain  rest_bp  chol  fbs                       rest_ecg  \
0   63  Male       typical      145   233    1  left ventricular hypertrophy    
1   67  Male  asymptomatic      160   286    0  left ventricular hypertrophy    

   max_hr  exang  old_peak  slope   ca    thal  disease  
0     150      0       2.3      3  0.0   fixed        0  
1     108      1       1.5      2  3.0  normal        1

In [35]:
cols = ['age', 'chol', 'old_peak', 'max_hr']
X = heart[cols].values
y = heart['disease'].values

In [36]:
from sklearn.linear_model import  LogisticRegression

In [37]:
logr = LogisticRegression()

In [38]:
X[:2]

array([[ 63. , 233. ,   2.3, 150. ],
       [ 67. , 286. ,   1.5, 108. ]])

In [40]:
logr.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [41]:
logr.score(X, y)

0.7227722772277227

In [42]:
logr.intercept_

array([0.77235092])

In [43]:
logr.coef_

array([[ 0.02215558,  0.00409133,  0.72787602, -0.02625114]])

In [63]:
V = np.array([55, 200, 2, 140])

In [64]:
V = V.reshape(1, -1)

In [65]:
V.ndim

2

In [66]:



logr.predict(V)

array([1])

In [67]:
c = np.array([[50, 200, 2, 140]])
c

array([[ 50, 200,   2, 140]])