In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

pd.options.display.max_columns = 200 
%matplotlib inline


In [3]:
heart = pd.read_csv('../data/heart.csv')
heart.head()

age     sex    chest_pain  rest_bp  chol  fbs  \
0   63    Male       typical      145   233    1   
1   67    Male  asymptomatic      160   286    0   
2   67    Male  asymptomatic      120   229    0   
3   37    Male    nonanginal      130   250    0   
4   41  Female    nontypical      130   204    0   

                        rest_ecg  max_hr  exang  old_peak  slope   ca  \
0  left ventricular hypertrophy      150      0       2.3      3  0.0   
1  left ventricular hypertrophy      108      1       1.5      2  3.0   
2  left ventricular hypertrophy      129      1       2.6      2  2.0   
3                         normal     187      0       3.5      3  0.0   
4  left ventricular hypertrophy      172      0       1.4      1  0.0   

         thal  disease  
0       fixed        0  
1      normal        1  
2  reversable        1  
3      normal        0  
4      normal        0

In [4]:
heart.shape

(303, 14)

In [5]:
dd = pd.read_csv('../data/heart_data_dictionary.csv')
dd

column name                                        description
0          age                                       age in years
1          sex                                     Male or Female
2   chest_pain      typical, asymptomatic, nonanginal, nontypical
3      rest_bp  resting blood pressure (in mm Hg on admission ...
4         chol                         serum cholestoral in mg/dl
5          fbs  (fasting blood sugar > 120 mg/dl) (1 = true; 0...
6     rest_ecg     resting electrocardiographic results (0, 1, 2)
7       max_hr                        maximum heart rate achieved
8        exang          exercise induced angina (1 = yes; 0 = no)
9     old_peak  ST depression induced by exercise relative to ...
10       slope          the slope of the peak exercise ST segment
11          ca  number of major vessels (0-3) colored by flour...
12        thal            normal, fixed defect, reversable defect
13     disease                                    1 = yes, 0 = no

In [6]:
heart.dtypes

age             int64
sex            object
chest_pain     object
rest_bp         int64
chol            int64
fbs             int64
rest_ecg       object
max_hr          int64
exang           int64
old_peak      float64
slope           int64
ca            float64
thal           object
disease         int64
dtype: object

In [8]:
import pandas_profiling as pf
pf.ProfileReport(heart)

In [10]:
heart.isna().sum()

age           0
sex           0
chest_pain    0
rest_bp       0
chol          0
fbs           0
rest_ecg      0
max_hr        0
exang         0
old_peak      0
slope         0
ca            4
thal          2
disease       0
dtype: int64

In [13]:
vc_ca = heart['ca'].value_counts()
vc_ca

0.0    176
1.0     65
2.0     38
3.0     20
Name: ca, dtype: int64

In [17]:
ca_fill = vc_ca.index[0]
ca_fill

0.0

In [16]:
vc_thal = heart['thal'].value_counts()
vc_thal

normal        166
reversable    117
fixed          18
Name: thal, dtype: int64

In [18]:
thal_fill = vc_thal.index[0]
thal_fill

'normal'

In [19]:
heart = heart.fillna({'ca':ca_fill, 'thal':thal_fill})
heart.head()

age     sex    chest_pain  rest_bp  chol  fbs  \
0   63    Male       typical      145   233    1   
1   67    Male  asymptomatic      160   286    0   
2   67    Male  asymptomatic      120   229    0   
3   37    Male    nonanginal      130   250    0   
4   41  Female    nontypical      130   204    0   

                        rest_ecg  max_hr  exang  old_peak  slope   ca  \
0  left ventricular hypertrophy      150      0       2.3      3  0.0   
1  left ventricular hypertrophy      108      1       1.5      2  3.0   
2  left ventricular hypertrophy      129      1       2.6      2  2.0   
3                         normal     187      0       3.5      3  0.0   
4  left ventricular hypertrophy      172      0       1.4      1  0.0   

         thal  disease  
0       fixed        0  
1      normal        1  
2  reversable        1  
3      normal        0  
4      normal        0

In [21]:
heart.isna().sum()

age           0
sex           0
chest_pain    0
rest_bp       0
chol          0
fbs           0
rest_ecg      0
max_hr        0
exang         0
old_peak      0
slope         0
ca            0
thal          0
disease       0
dtype: int64

In [22]:
heart['ca'] = heart['ca'].astype('int')
heart.dtypes

age             int64
sex            object
chest_pain     object
rest_bp         int64
chol            int64
fbs             int64
rest_ecg       object
max_hr          int64
exang           int64
old_peak      float64
slope           int64
ca              int64
thal           object
disease         int64
dtype: object

In [23]:
X = heart['age'].values
y = heart['disease'].values

In [24]:
type(X)

numpy.ndarray

In [25]:
type(y)

numpy.ndarray

In [26]:
X[:5]

array([63, 67, 67, 37, 41])

In [27]:
y[:5]

array([0, 1, 1, 0, 0])

In [36]:
from sklearn.linear_model import LogisticRegression


In [37]:
logr = LogisticRegression()

In [38]:
X.ndim

1

In [41]:
X = X.reshape(-1, 1)
X[:5]

array([[63],
       [67],
       [67],
       [37],
       [41]])

In [42]:
X.shape

(303, 1)

In [43]:
X.ndim


2

In [44]:
logr.fit(X, y)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [46]:
X.min(), X.max()

(29, 77)